# version: '2'

services:
  mysql:
    #   image: mysql:5.7
    image: mariadb:10.5.8
    volumes:
      # if you need to load the database from an export, uncomment this line and place the sqldump in mysql_dump
      - ./mysql_dump:/docker-entrypoint-initdb.d
      - ./backend/data_volume:/var/lib/mysql
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.react
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.django
    volumes:
      - "./backend:/backend"
    ports:
      - 8000:8000
    entrypoint: "pipenv run python manage.py runserver 0.0.0.0:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SITE_NAME=${SITE_NAME}
      - SITE_TITLE=${SITE_TITLE}
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/development:/etc/nginx/conf.d
    environment:
      - REACT_APP_LOGO_PRIMARY=${REACT_APP_LOGO_PRIMARY}
      - REACT_APP_LOGO_SMALL=${REACT_APP_LOGO_SMALL}
    depends_on:
      - frontend
      - backend
