# version: "2"

services:
  mysql:
    #   image: mysql:5.7
    image: mariadb:10.5.8
    volumes:
      - ./mysql_dump:/docker-entrypoint-initdb.d
      - ./backend/data_volume:/var/lib/mysql
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-stage}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  nginx:
    # restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/production:/etc/nginx/conf.d
    depends_on:
      - backend
    environment:
      - NGINX_PORT=${NGINX_PORT}
  backend:
    # restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.django
    expose:
      - 8000
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-stage}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DEBUG_STATUS=${DEBUG_STATUS}
