# Generated by Django 3.2.7 on 2021-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
