# Generated by Django 3.2.8 on 2021-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='title_eng',
        ),
    ]
