# Generated by Django 3.2.8 on 2021-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20211019_1315'),
        ('timemap', '0010_auto_20211019_1315'),
        ('data', '0002_rename_title_image_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='articles',
            field=models.ManyToManyField(to='article.Article'),
        ),
        migrations.AddField(
            model_name='image',
            name='copyright_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright Status'),
        ),
        migrations.AddField(
            model_name='image',
            name='periods',
            field=models.ManyToManyField(blank=True, to='timemap.Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='permission_notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Permissions notes'),
        ),
        migrations.AddField(
            model_name='image',
            name='places',
            field=models.ManyToManyField(blank=True, to='timemap.Place'),
        ),
        migrations.AddField(
            model_name='image',
            name='rights_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rights Holder'),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='image',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='image',
            name='title_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='image',
            name='title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (French)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title_eng',
            field=models.CharField(max_length=255, verbose_name='Title (English)'),
        ),
    ]
