# Generated by Django 3.2.9 on 2021-12-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_image_arkid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='articles',
        ),
    ]
