# Generated by Django 3.2.7 on 2022-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('data', '0007_alter_image_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='collection',
            field=models.ManyToManyField(blank=True, to='collection.Collection'),
        ),
    ]
