# Generated by Django 3.2.7 on 2022-06-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_image_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Credit line'),
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.TextField(blank=True, help_text="Date the original resource was created formatted as YYYY MM/DD. If month or day are not known, just enter the year (i.e. '2022 06' or '2022')", max_length=255, null=True, verbose_name='Date created'),
        ),
        migrations.AddField(
            model_name='image',
            name='endDate',
            field=models.TextField(blank=True, help_text="Include an end date if a specific year is known; otherwise, just set the end period. Format the value as YYYY MM/DD. If month or day are not known, just enter the year (i.e. '2022 06' or '2022')", null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='image',
            name='startDate',
            field=models.TextField(blank=True, help_text="Include a start date if a specific year is known; otherwise, just set the start period. Format the value as YYYY MM/DD. If month or day are not known, just enter the year (i.e. '2022 06' or '2022')", null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='arkID',
            field=models.CharField(blank=True, help_text='Add the Ark ID for this resource from the UCLA Library digital asset mananagement system (i.e. ark:/21198/zz000rwn8d)', max_length=255, null=True, verbose_name='ArkID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Caption'),
        ),
    ]
