# Generated by Django 3.2.7 on 2022-06-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20220621_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='image',
            name='endDate',
            field=models.CharField(blank=True, help_text="Include an end date if a specific year is known; otherwise, just select the appropriate period. Format the value as YYYY MM/DD. If month or day are not known, just enter the year (i.e. '2022 06' or '2022')", max_length=255, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='startDate',
            field=models.CharField(blank=True, help_text="Include a start date if a specific year is known; otherwise, just select the approproate period. Format the value as YYYY MM/DD. If month or day are not known, just enter the year (i.e. '2022 06' or '2022')", max_length=255, null=True, verbose_name='Start date'),
        ),
    ]
