# Generated by Django 3.2.7 on 2021-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Glossary Terms',
            },
        ),
    ]
