# Generated by Django 3.2.7 on 2021-10-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'verbose_name_plural': 'Glossary terms'},
        ),
    ]
