# Generated by Django 3.2.7 on 2022-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_alter_glossaryterm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Definition (Arabic)'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='definition_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Definition (English)'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Term (Arabic)'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='term_eng',
            field=models.CharField(default='needs review', max_length=255, verbose_name='Term (English)'),
            preserve_default=False,
        ),
    ]
