# Generated by Django 3.2.7 on 2022-05-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_auto_20220531_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glossaryterm',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='glossaryterm',
            name='name_eng',
        ),
    ]
