# Generated by Django 3.2.7 on 2022-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_alter_glossaryterm_term_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryterm',
            name='alternative_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative term name(s) (Arabic)'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='alternative_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative term name(s) (English)'),
        ),
    ]
