# Generated by Django 3.2.7 on 2022-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_eng', models.CharField(max_length=255, unique=True, verbose_name='Collection Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection Title (Arabic)')),
                ('title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection Title (German)')),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection Title (French)')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source')),
                ('collection_creator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Collection Curator')),
            ],
        ),
    ]
