# Generated by Django 3.2.5 on 2021-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='altnames_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative names (Arabic)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='altnames_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative names (English)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='place_children', to='timemap.Place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='place_parents', to='timemap.Place'),
        ),
    ]
