# Generated by Django 3.2.5 on 2021-08-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_remove_article_place'),
        ('timemap', '0005_place_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Construction', 'Construction'), ('Destruction', 'Destruction'), ('Inactive / defunct', 'Inactive / defunct'), ('Modification', 'Modification'), ('In use', 'In use')], default='In use', max_length=200)),
                ('startDate', models.IntegerField(null=True)),
                ('endDate', models.IntegerField(null=True)),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_eng', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('altnames_eng', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative names (English)')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Name (Arabic)')),
                ('altnames_ar', models.CharField(blank=True, max_length=500, null=True, verbose_name='Alternative names (Arabic)')),
                ('isRegion', models.BooleanField(default=False)),
                ('isGovernate', models.BooleanField(default=False)),
                ('isNome', models.BooleanField(default=False)),
                ('isSite', models.BooleanField(default=False)),
                ('isFeature', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lon', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.ManyToManyField(blank=True, to='timemap.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='associatedFeature',
        ),
        migrations.RemoveField(
            model_name='event',
            name='associatedPlace',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endDynasty',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endPhase',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endReign',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDynasty',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startPhase',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startReign',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='site',
        ),
        migrations.RemoveField(
            model_name='place',
            name='children',
        ),
        migrations.RemoveField(
            model_name='place',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='place',
            name='period',
        ),
        migrations.RemoveField(
            model_name='reign',
            name='dynasty',
        ),
        migrations.DeleteModel(
            name='Dynasty',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Reign',
        ),
        migrations.AddField(
            model_name='activity',
            name='associatedLocation',
            field=models.ManyToManyField(to='timemap.Location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='endPeriod',
            field=models.ManyToManyField(related_name='endPeriod', to='timemap.Period'),
        ),
        migrations.AddField(
            model_name='activity',
            name='startPeriod',
            field=models.ManyToManyField(related_name='startPeriod', to='timemap.Period'),
        ),
    ]
