# Generated by Django 3.2.5 on 2021-08-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0006_auto_20210805_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='period',
        ),
    ]
