# Generated by Django 3.2.5 on 2021-08-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0007_remove_location_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
