# Generated by Django 3.2.7 on 2021-10-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0016_auto_20211019_1315"),
        ("timemap", "0009_auto_20210806_1031"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Place",
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="associatedLocation",
            new_name="associatedPlace",
        ),
    ]
