# Generated by Django 3.2.7 on 2022-06-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0010_auto_20211019_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endPeriod',
            field=models.ManyToManyField(blank=True, related_name='endPeriod', to='timemap.Period'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startPeriod',
            field=models.ManyToManyField(blank=True, related_name='startPeriod', to='timemap.Period'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name_eng',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_eng',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name (English)'),
        ),
    ]
