# Generated by Django 3.2.7 on 2023-02-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0011_auto_20220603_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endDate',
            field=models.IntegerField(blank=True, help_text='Include an end date if a specific year is known; otherwise, just set the end period.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startDate',
            field=models.IntegerField(blank=True, help_text='Include a start date if a specific year is known; otherwise, just set the start period.', null=True),
        ),
    ]
