# Build React static files
FROM node:16-buster-slim

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm install --legacy-peer-deps

# add app
COPY ./frontend/ ./

# start app development server
CMD ["npm", "start"]