# Generated by Django 3.2.5 on 2021-07-13 01:28

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name_eng",
                    models.CharField(max_length=200, verbose_name="Name (English)"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="Name (Arabic)"),
                ),
                (
                    "keyword_type",
                    models.CharField(
                        choices=[
                            ("Places", "Places"),
                            ("Periods", "Periods"),
                            ("Glossary terms", "Glossary terms"),
                        ],
                        default="Glossary terms",
                        max_length=200,
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title_eng",
                    models.CharField(max_length=200, verbose_name="Title (English)"),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Title (Arabic)"),
                ),
                (
                    "title_de",
                    models.CharField(max_length=200, verbose_name="Title (German)"),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Title (French)"),
                ),
                ("abstract_eng", models.TextField(max_length=1500)),
                ("abstract_ar", models.TextField(max_length=1500)),
                (
                    "status",
                    models.CharField(
                        choices=[("U", "Unpublished"), ("P", "Published")],
                        default="U",
                        max_length=100,
                    ),
                ),
                ("body", markdownx.models.MarkdownxField()),
                ("authors", models.ManyToManyField(to="article.Author")),
                ("keywords", models.ManyToManyField(to="article.Keyword")),
            ],
        ),
    ]
