# Generated by Django 3.2.5 on 2021-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_subjectarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject_area',
            field=models.ManyToManyField(to='article.SubjectArea'),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='name_ar',
            field=models.CharField(max_length=200, verbose_name='Subject (Arabic)'),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='name_de',
            field=models.CharField(max_length=200, verbose_name='Subject (German)'),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='name_eng',
            field=models.CharField(max_length=200, verbose_name='Subject (English)'),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='name_fr',
            field=models.CharField(max_length=200, verbose_name='Subject (French)'),
        ),
        migrations.AlterField(
            model_name='subjectarea',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='subjectArea_parent', to='article.SubjectArea'),
        ),
    ]
