# Generated by Django 3.2.5 on 2021-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210713_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subject_test',
            field=models.ManyToManyField(to='article.TreeTest'),
        ),
    ]
