# Generated by Django 3.2.5 on 2021-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_subject_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subject_test',
        ),
        migrations.RemoveField(
            model_name='subjectarea',
            name='parent',
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectarea',
            name='path',
            field=models.CharField(default='0000', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TreeTest',
        ),
    ]
