# Generated by Django 3.2.5 on 2021-08-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='place',
        ),
    ]
