# Generated by Django 3.2.5 on 2021-08-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0006_auto_20210805_1502'),
        ('article', '0008_remove_article_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ManyToManyField(to='timemap.Location'),
        ),
    ]
