# Generated by Django 3.2.6 on 2021-08-13 20:05

from django.db import migrations
# import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_location'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='article',
        #     name='treeWidgetTest',
        #     field=treewidget.fields.TreeManyToManyField(blank=True, related_name='widgetTest', to='article.SubjectArea'),
        # ),
    ]
