# Generated by Django 3.2.6 on 2021-08-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_treewidgettest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255, verbose_name='Author(s)')),
                ('year', models.CharField(max_length=20, verbose_name='Year')),
                ('publication_info', models.TextField(max_length=500, verbose_name='Publication information')),
            ],
        ),
    ]
