# Generated by Django 3.2.6 on 2021-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Persistent URL'),
        ),
    ]
