# Generated by Django 3.2.7 on 2021-09-02 20:32

from django.db import migrations
# import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_reference_article'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='article',
        #     name='treeWidgetTest',
        #     field=treewidget.fields.TreeManyToManyField(blank=True, related_name='widgetTest', to='article.SubjectArea'),
        # ),
    ]
