# Generated by Django 3.2.7 on 2021-10-19 20:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timemap", "0009_auto_20210806_1031"),
        ("article", "0015_remove_article_treewidgettest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="location",
            new_name="place",
        ),
        migrations.AlterField(
            model_name="reference",
            name="publication_info",
            field=ckeditor.fields.RichTextField(verbose_name="Publication information"),
        ),
    ]
