# Generated by Django 3.2.8 on 2021-11-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20211019_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
