# Generated by Django 3.2.7 on 2022-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemap', '0010_auto_20211019_1315'),
        ('article', '0017_auto_20211101_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='activity',
            field=models.ManyToManyField(to='timemap.Activity'),
        ),
    ]
