# Generated by Django 3.2.7 on 2022-06-08 18:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('article', '0020_auto_20220607_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ManyToManyField(blank=True, to='collection.Collection'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
