# Generated by Django 3.2.7 on 2023-02-10 00:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20220608_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='article',
            field=models.ManyToManyField(blank=True, help_text='Select the article(s) this resource is referenced in - if an article is already selected, be sure to hold Control or Command when selecting an additional article.', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='publication_info',
            field=ckeditor.fields.RichTextField(help_text='Enter the rest of the reference citation, following the bibliographic style used by the author (i.e. Form, fabric and function: Some observations on the cooking pot in antiquity, In\xa0Technology and style 2, Ceramics and Civilization. ed. W. David Kingery , pp. 157 - 172. Columbus: American Ceramic Society.', verbose_name='Publication information'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.URLField(blank=True, help_text='If a DOI or other type of persistent identifier is available, add the DOI label here (i.e. doi:0000000/000000000000)', null=True, verbose_name='Persistent URL'),
        ),
    ]
