# Generated by Django 3.2.9 on 2021-12-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('body', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('U', 'Unpublished'), ('P', 'Published')], default='U', max_length=255)),
            ],
        ),
    ]
