# Generated by Django 3.2.9 on 2021-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_basicpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
