# Generated by Django 3.2.7 on 2023-02-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_basicpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='slug',
            field=models.CharField(blank=True, help_text='Enter a word or short phrase separated by dashes to set the url for this page (i.e. new-page). Notify the technical team whenever adding a new page.', max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
